version: "3.3"

services:
  nextjs:
    image: gas-portal
    ports:
      - 3100:3000
    build:
      context: ./
      dockerfile: Dockerfile
    # environment: 
    #   - APP_API_BASE_URL=$${APP_API_BASE_URL}  
    volumes:
      - ./packages/gasd-potech:/app
      - /app/.next
    env_file:
      - .env.development